# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-27 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon', models.TextField()),
                ('tues', models.TextField()),
                ('wed', models.TextField()),
                ('thurs', models.TextField()),
                ('fri', models.TextField()),
                ('sat', models.TextField()),
                ('sun', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('cuisine', models.CharField(max_length=255)),
                ('services', models.CharField(max_length=255)),
                ('drange', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ManyToManyField(related_name='restaddress', to='userapp.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=255)),
                ('l_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('cpassword', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.ManyToManyField(related_name='vendoraddress', to='userapp.Address')),
                ('rest', models.ManyToManyField(related_name='vendor', to='vendorapp.Restaurant')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='rest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='vendorapp.Restaurant'),
        ),
    ]
