# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressNumber', models.CharField(max_length=10)),
                ('addressNumberPrefix', models.CharField(max_length=20)),
                ('addressNumberSuffix', models.CharField(max_length=20)),
                ('buildingName', models.CharField(max_length=10)),
                ('occupancyType', models.CharField(max_length=20)),
                ('occupancyIdentifier', models.CharField(max_length=20)),
                ('placeName', models.CharField(max_length=20)),
                ('stateName', models.CharField(max_length=20)),
                ('streetName', models.CharField(max_length=20)),
                ('streetNamePreDirectional', models.CharField(max_length=20)),
                ('streetNamePreType', models.CharField(max_length=20)),
                ('streetNamePostDirectional', models.CharField(max_length=20)),
                ('streetNamePostType', models.CharField(max_length=20)),
                ('subaddressType', models.CharField(max_length=20)),
                ('uSPSBoxType', models.CharField(max_length=20)),
                ('zipCode', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('l_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('code', models.CharField(max_length=6)),
                ('valid', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
                ('address', models.ManyToManyField(related_name='useraddress', to='userapp.Address')),
            ],
        ),
    ]
